# Your project's root directory:
# root: /alchemy/site
root: ''

# Your information:
title: Site title
email: jack@jackcrane.rocks
description: >- # this means to ignore newlines until "baseurl:"
  A modern, fast, easy-to-use jekyll alternative based on Javascript and EJS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alchemy.jackcrane.rocks"

author:
  name: Jack Crane
  email: jack@jackcrane.rocks

socials:
  - type: github
    link: https://github.com/jackcrane
    username: jackcrane
  - type: instagram
    link: https://www.instagram.com/jackcraneb/
    username: jackcraneb
  - type: twitter
    link: https://www.twitter.com/howdyitsjack
    username: howdyitsjack

bmac:
  type: button
  username: jackcrane
  color: '#FFDD00'
  message: Feeling Generous?

tags: jack crane, software engineering, web development